site_name: Full Stack Curriculum
theme:
  name: material
  logo: assets/home_logo.png
  favicon: assets/favicon.png
  palette:
    # Dark mode (default)
    - scheme: slate
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light mode
    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  font:
    text: Roboto Condensed
    code: Roboto Mono

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.footer

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CodePlatoon/se-curriculum
    - icon: fontawesome/brands/slack
      link: https://codeplatoonteam.slack.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@CodePlatoon

nav:
  - Home: index.md
  - Installfest: 
    - Installfest - Overview: Installfest/README.md
    - Preparing Your Machine: Installfest/1-preparing-your-machine.md
    - Command Line Interface: Installfest/2-command-line-interface.md
    - Manual Installment: Installfest/3-manual-installment.md
    - Dev Containers: Installfest/4-dev-containers.md
    - Interacting with Assignments: Installfest/5-interacting-with-assignments.md
    - Assignments: Installfest/assignments.md
  - Phase I: 
    - Phase I - Overview: phase-I/README.md
    - Fundamentals:
      - Fundamentals - Overview: phase-I/01-Fundamentals/README.md
      - Docker:
        - Docker - Overview: phase-I/01-Fundamentals/1-docker/README.md
        - Intro to Docker: phase-I/01-Fundamentals/1-docker/1-intro-to-docker.md
        - Leveraging Docker: phase-I/01-Fundamentals/1-docker/2-leveraging-docker.md
        - Docker Assignments: phase-I/01-Fundamentals/1-docker/assignments.md
      - Git & Github: 
        - Git & Github - Overview: phase-I/01-Fundamentals/2-git-and-github/README.md
        - Git Fundamentals: phase-I/01-Fundamentals/2-git-and-github/1-git-fundamentals.md
        - Github Fundamentals: phase-I/01-Fundamentals/2-git-and-github/2-github-fundamentals.md
        - Git Assignments: phase-I/01-Fundamentals/2-git-and-github/assignments.md
      - JS & Python:
        - JS & Python - Overview: phase-I/01-Fundamentals/3-js-python/README.md
        - JS & Python Fundamentals: phase-I/01-Fundamentals/3-js-python/1-js-python-fundamentals.md
        - Functional Programming: phase-I/01-Fundamentals/3-js-python/2-functional-programming.md
        - JS & Python Assignments: phase-I/01-Fundamentals/3-js-python/assignments.md
      - TDD:
        - TDD - Overview: phase-I/01-Fundamentals/4-tdd/README.md
        - Intro to TDD with PyTest: phase-I/01-Fundamentals/4-tdd/1-intro-to-tdd-w-pytest.md
        - TDD with Jest: phase-I/01-Fundamentals/4-tdd/2-tdd-w-jest.md
        - TDD Assignments: phase-I/01-Fundamentals/4-tdd/assignments.md
      - Github Actions:
        - GH Actions - Overview: phase-I/01-Fundamentals/5-github-actions/README.md
        - Intro to Workflows: phase-I/01-Fundamentals/5-github-actions/1-intro-to-workflows.md
        - Managing Workflows: phase-I/01-Fundamentals/5-github-actions/2-managing-workflows.md
        - GH Actions Assignments: phase-I/01-Fundamentals/5-github-actions/assignments.md
      - Team Kickoff:
        - Team Kickoff - Overview: phase-I/01-Fundamentals/6-team-kickoff/README.md
        - Retention Assignments: phase-I/01-Fundamentals/6-team-kickoff/assignments.md
    - OOP: 
      - OOP Overview: phase-I/02-OOP/README.md
      - Intro to OOP:
        - Intro to OOP - Overview: phase-I/02-OOP/1-oop-intro/README.md
        - OOP with Python: phase-I/02-OOP/1-oop-intro/1-intro-python-oop.md
        - Getters & Setters: phase-I/02-OOP/1-oop-intro/2-encapsulation-get-set.md
        - Intro to OOP - Assignments: phase-I/02-OOP/1-oop-intro/assignments.md
      - Class vs Instance:
        - Class vs Instance - Overview: phase-I/02-OOP/2-abstraction-encapsulation/README.md
        - cls vs self - attributes: phase-I/02-OOP/2-abstraction-encapsulation/1-attributes-cls-vs-self.md
        - cls vs self - methods: phase-I/02-OOP/2-abstraction-encapsulation/2-methods-static-cls-self.md
        - Class vs Instance - Assignments: phase-I/02-OOP/2-abstraction-encapsulation/assignments.md
      - Inheritance & Polymorphism:
        - Inheritance & Polymorphism - Overview: phase-I/02-OOP/3-inheritance-polymorphism/README.md
        - OOP Inheritance: phase-I/02-OOP/3-inheritance-polymorphism/1-oop-inheritance.md
        - OOP Polymorphism: phase-I/02-OOP/3-inheritance-polymorphism/2-oop-polymorphism.md
        - Inheritance & Polymorphism - Assignments: phase-I/02-OOP/3-inheritance-polymorphism/assignments.md
    - DS & Algorithms: 
      - DS & Algorithms - Overview: phase-I/03-DS-Algorithms/README.md
      - Binary vs Linear Search: phase-I/03-DS-Algorithms/01-binary-vs-linear-search/README.md
      - Binary vs Linear Search - Assignments: phase-I/03-DS-Algorithms/01-binary-vs-linear-search/assignments.md
      - Understanding Big-O: phase-I/03-DS-Algorithms/02-big-o/README.md
      - Big-O - Assignments: phase-I/03-DS-Algorithms/02-big-o/assignments.md
      - Stacks & Queues: phase-I/03-DS-Algorithms/03-stacks-and-queues/README.md
      - Stacks & Queues - Assignments: phase-I/03-DS-Algorithms/03-stacks-and-queues/assignments.md
      - Recursion: phase-I/03-DS-Algorithms/04-recursion/README.md
      - Recursion - Assignments: phase-I/03-DS-Algorithms/04-recursion/assignments.md
      - Sorting Algorithms: phase-I/03-DS-Algorithms/05-sorting-algos/README.md
      - Sorting Algorithms - Assignments: phase-I/03-DS-Algorithms/05-sorting-algos/assignments.md
      - Divide & Conquer Algorithms: phase-I/03-DS-Algorithms/06-div-conquer-algos/README.md
      - Divide & Conquer Algorithms - Assignments: phase-I/03-DS-Algorithms/06-div-conquer-algos/assignments.md
      - Memory & Linked List: phase-I/03-DS-Algorithms/07-memory-linked-list/README.md
      - Memory & Linked List - Assignments: phase-I/03-DS-Algorithms/07-memory-linked-list/assignments.md
      - Circular & Doubly Linked List: phase-I/03-DS-Algorithms/08-circular-doubly-linked-lists/README.md
      - Circular & Doubly Linked List - Assignments: phase-I/03-DS-Algorithms/08-circular-doubly-linked-lists/assignments.md
      - Binary Trees: phase-I/03-DS-Algorithms/09-binary-trees/README.md
      - Binary Trees - Assignments: phase-I/03-DS-Algorithms/09-binary-trees/assignments.md
      - DFS vs BFS: phase-I/03-DS-Algorithms/10-dfs-vs-bfs/README.md
      - DFS vs BFS - Assignments: phase-I/03-DS-Algorithms/10-dfs-vs-bfs/assignments.md
      - Technical Interview: phase-I/03-DS-Algorithms/11-technical-interview/README.md
      - DS & Algorithms - Assignments: phase-I/03-DS-Algorithms/assignments.md
  - Phase II:
      - Phase II - Overview: phase-II/README.md
      - Full Stack Development:
        - Full Stack Development Overview: phase-II/Intro-to-FS-Dev/README.md
        - Full Stack Development Workflow: phase-II/Intro-to-FS-Dev/1-fs-workflow.md
        - Full Stack Development Breakdown: phase-II/Intro-to-FS-Dev/2-fs-breakdown.md
  - Phase III: phase-III
  - Phase IV: phase-IV
  - Phase V: phase-V
  - Additional Lectures: additional-lectures