site_name: Full Stack Curriculum
theme:
  name: material
  logo: assets/home_logo.png
  favicon: assets/favicon.png
  palette:
    # Dark mode (default)
    - scheme: slate
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light mode
    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  font:
    text: Roboto Condensed
    code: Roboto Mono

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.footer

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CodePlatoon/se-curriculum
    - icon: fontawesome/brands/slack
      link: https://codeplatoonteam.slack.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@CodePlatoon

nav:
  - Home: index.md
  - Installfest: 
    - Installfest - Overview: Installfest/README.md
    - Preparing Your Machine: Installfest/1-preparing-your-machine.md
    - Command Line Interface: Installfest/2-command-line-interface.md
    - Manual Installment: Installfest/3-manual-installment.md
    - Dev Containers: Installfest/4-dev-containers.md
    - Interacting with Assignments: Installfest/5-interacting-with-assignments.md
    - Assignments: Installfest/assignments.md
  - Phase I: 
    - Phase I - Overview: phase-I/README.md
    - Fundamentals:
      - Fundamentals - Overview: phase-I/01-Fundamentals/README.md
      - Docker:
        - Docker - Overview: phase-I/01-Fundamentals/1-docker/README.md
        - Intro to Docker: phase-I/01-Fundamentals/1-docker/1-intro-to-docker.md
        - Leveraging Docker: phase-I/01-Fundamentals/1-docker/2-leveraging-docker.md
        - Docker Assignments: phase-I/01-Fundamentals/1-docker/assignments.md
      - Git & Github: 
        - Git & Github - Overview: phase-I/01-Fundamentals/2-git-and-github/README.md
        - Git Fundamentals: phase-I/01-Fundamentals/2-git-and-github/1-git-fundamentals.md
        - Github Fundamentals: phase-I/01-Fundamentals/2-git-and-github/2-github-fundamentals.md
        - Git Assignments: phase-I/01-Fundamentals/2-git-and-github/assignments.md
      - JS & Python:
        - JS & Python - Overview: phase-I/01-Fundamentals/3-js-python/README.md
        - JS & Python Fundamentals: phase-I/01-Fundamentals/3-js-python/1-js-python-fundamentals.md
        - Functional Programming: phase-I/01-Fundamentals/3-js-python/2-functional-programming.md
        - JS & Python Assignments: phase-I/01-Fundamentals/3-js-python/assignments.md
      - TDD:
        - TDD - Overview: phase-I/01-Fundamentals/4-tdd/README.md
        - Intro to TDD with PyTest: phase-I/01-Fundamentals/4-tdd/1-intro-to-tdd-w-pytest.md
        - TDD with Jest: phase-I/01-Fundamentals/4-tdd/2-tdd-w-jest.md
        - TDD Assignments: phase-I/01-Fundamentals/4-tdd/assignments.md
    - OOP: phase-I/02-OOP/README.md
    - DS & Algorithms: phase-I:/03-DS-Algorithms/README.md
  - Phase II: phase-II
  - Phase III: phase-III
  - Phase IV: phase-IV
  - Phase V: phase-V
  - Additional Lectures: additional-lectures