# docker-compose.yml

# version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
#    env_file:
    #  - .env
    depends_on:
      - db

  frontend:
    build: ./frontend/my-react-app
    command: npm run dev
    volumes:
      - ./frontend/my-react-app:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

volumes:
  postgres_data: